volodymyr = User.create!(username: 'Volodymyr', email: 'volodymyr@example.com', password: 'mypass', role: 'admin')
iryna = User.create!(username: 'Iryna', email: 'iryna@example.com', password: 'ho#ll_§1', role: 'admin')
v1 = volodymyr.accounts.create(currency: 'UAH', balance: 10_000)
v2 = volodymyr.accounts.create(currency: 'USD', balance: 1000)
i1 = iryna.accounts.create(currency: 'UAH', balance: 20_000)
i2 = iryna.accounts.create(currency: 'USD', balance: 2000)
v1.transactions.create(operation: 'Withdraw', amount: 1000)
v2.transactions.create(operation: 'Deposit', amount: 2000)
i1.transactions.create(operation: 'Withdraw', amount: 3000)
i2.transactions.create(operation: 'Withdraw', amount: 5000)