volodymyr = User.create(username: 'Volodymyr', email: 'volodymyr@example.com', password: 'mypass', role: 'admin')
iryna = User.create(username: 'Iryna', email: 'iryna@example.com', password: 'ho#ll_§1', role: 'admin')
Account.create(user_id: volodymyr.id, currency: 'UAH', amount: 10_000)
Account.create(user_id: volodymyr.id, currency: 'USD', amount: 1000)
Account.create(user_id: iryna.id, currency: 'UAH', amount: 20_000)
Account.create(user_id: iryna.id, currency: 'USD', amount: 2000)